services:
    app.admin.bundle_view:
        class: S3Bundle\Admin\BucketViewAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Bucket, label: Bucket View }
        arguments:
            - null
            - null
            - S3Bundle:BucketView
        public: true
    app.amazon.s3:
        class: S3Bundle\Service\AmazonS3
        arguments: [%amazon_s3_region%, %amazon_s3_key%, %amazon_s3_secret%]
